"use client";

import { useEffect, useRef } from "react";

// Pre-computed audio spectrum: 121 frames x 40 bars @ 20fps
const SPECTRUM_B64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEAAQEBAQEAWwCAiAByPjY4NiRDTVNLb3t5TYmLh2OYeoSYdHBwgnZwW3ZUQz4fALMAraUAmFA3OD0sR1laU3mGi12flZx4qImZq4KEgZ+Xim+IZlJSOABuAEg2ADggDRERDRIcFxUcIyIoLhwoJC8mKycmKSY6OS0mJyEdISAAQAArLAAiGREWEgsTFBYSFyIWJCAZHRorICMiIyQjLSwjHCAYFhcWAD0ANE8ATCEfIB0SExAUDxUdISMgHh0ZIRscHxweHCAjHRgdFhYbHQApAC5EAEIVGRwUExcPEg4UFyMgHxocFBUTFBUTExMWGBMRFRETFhoAFgAdIAAcCAsOCA8VCg8MERIZHBQTFw4LDA8PDAsNDhAMCQ4KDA4QAEMAWGoAinR9jpqdo52enKKjenGGiaSgl5SUaZ6Sn5CVnZygnZ+YnAAuAEdwAKZ+fIiWp56fsaigoIqrraa7qrC7v5CvqcGyr8O60r3Q2dwAGAAjTQBYSUU9MlFJSlhLSFNqi2ZsXUlibYhuWFd9eoFwapdxmaiqABYAFzEAKTEwLyU6PjQwLjZFUlNARzkzP0dfU0dBWFhrSU9uV3R1dwAsAD5SAFIrIzAyMzsrLSg0SE1RTD9AMzc5S0M9PDg8Szs7UEJTVlkAIwA4SgBEIh8hIhwlIyUcJi80MjUuLiEpJTAsJiMjJjMoJTIoNjk5AA4AFyMAIBAMCw0NERMSDxQSFR0eGRgSFxkZHxkVGRkjGhshGyUlIwAhADFLAFI5LjM2P0M1NjpZgo11TWWIQFxpZmxmSWRtlXdgalR1eGEAZQCTeABvUEM+PkhTPDpBaZKrdWCEo2ZxfnuKhHyDktunhpZ1jZBwAFgAhlEAVTYsJRsdIR8UHzVCSjZLR01LRDs/TVRWU2WQdFdsUFVWRwA3AE8sADAfGx0aFBkbGBonOEE6QTpFNkE4OkJLQ0xkfGlNaURKTUIATABnXQBJIR0uNDA8Mi8oNVFpYVRRVDFEPEFDO0NFXW5jUmVBTExIACgAREAARh8YJCgpLCchISpASUQ4NzwgLiAsKSYkKTpAPDY5KDExMAASAB0WACEOCw4NDxAQDA0RGBgdGRgcEhkRGh0aFhwnLSMgJhkcHBsAKwAwLgA3ICMoLDtKQ0A/R0pCSkpGT0VINUI7RDVBTVBPSFJGSEVHACIAM2EAdk9JPj1oakhmbGJ6fGp6cG5jdGdpeGVVcHV6emyYcZKXlgAeAD+KAI9ZXEs0XFg4b2tseX1vf2FpZGqIgolvZIKGjoNzuoOmr7cAGAArSgBKMzozIy07ME5FUUxOWEw1T0xGYGlVVk5XYG1cVX1feniEACQAMEQASi4uNzVBVkFCQ1Zqf4RoV11GUUJWSkRBR1NgSkVbR2tqbQA1AERKADUjHysrNz40LzNBTV5cVERBMDosPjcuJS44OysuPi89QUIAJgAgIwAYFQ4QEBMUFBMYFRIaICEWGBYcGiUgHhYYHyMbHCgeJCcmAB0AEB4AKxYYFhcaHBcYGhkgIzM0JB4aIh0pJSUfIisxJyIzJy82NACNAG9dAFczICchKTksNiYuPzJPPjo3NjwuMEU6Q0dOTTw4Ri8yNjkAhABXUwA9KhcfGiM5Ji8fIS4yQCcsNjEyLDJEMzo/RT41NDwoJiQnADUAISgAHBUSEAwSIBMYEhATJCoXGSYdHB8mKyEhJC4mIiIoHBgXFgAtADEvADonJSgtNkIzNTpGWGttXU9SNjoqLjkvKCMvMiYqLSIlJigALAA/PQA6KBwiKjE7MDI2PlZqYFtHSS0zIyczJh8dJSseISYfISQrAB8AJSsAIBEKDAoMERARExMZISIdExgQFBARGBEREhUWDw8UEBEUGAApACAwACwNERQTEhUVExcgKCQuJB4hFRwUFRwXFBUXGhQTGREVGx8AKwBJdACEWFcyNkpHJz9BREtham9TPEhQWF5mT05LWXBWQGpLd39wACEASncAl3RWTUJTZzhnWWhsho+XdGlpcIaik3hyfoueinOzfbzDvwAPACA1AEE3HzIiK0EpTjZCTV5bWU1SQklVe19WTFZqb2VgiF99go8AGgAqMwA9JCs0Jzk7K0s3Qlx+cnJmWEJMTG1ZUE5OaGlWWHNUa3h3ACoAVkwAUyspLikrKiQ4KjlLYmNfWEw0QkRKQzw8RExKOkNSPVFgVAAhAEBBADohHRgUEhUUGRceHi4uKiEgGSImISYiHyMpMCQjLyMvMy8AIgAoMwA4HhwdFRYdFg8XJiU4NzwhJx0gJCQmJCQlKzcnITEmMTM1AKYApJcAgVVDNzphbUVNR0hxr6huZohYfGGFf3JpdXScaFqAWmJmggDEAKyVAGpDNC00W1xCTkI9Y5eMWmmJU3Nfe4F3bHp8p3dvi11jZ3YAcgBiUgA1GxobFyIcGx0dHSg2PC09QCs3NTxGRUNRYXhnXGVDS0s/AGEAdFoAQyMuHh8fJxojKTRHaXVfVE5EXUdhXlZXa4aPlnV+VmljUgB3AIBhAGQrKhQgGDIgLiY5TGpuY09RRmdEXmtXU2Jre3toa09WWEgAWQBcRgBNJB0REA4iGB4ZJDA/NC0lKilBKzZFNjY/RlFDOkA3NTo8AEMAPDgANSIcFBEWJhUcFys4Rz43IyswPzRAPzk3OUlQQTlBNzY6OABLAFdIAIKLjoh/dmd8Z3xvgF1ve3t7fpWIm36RgIiAmY+LjImNm48AOgBbbQC1mpOTjJB3ooyUeJJyh5WTlJ2yl8qrnI6drreroLqqwdfOABoAKkkAVD0wLitDQEhOPz1OXVpXUFJQXlx5gFNNWXh/aGCHcYiUmQAbABsiABwiISAfMDQnKysxQVZGREE/K0JUU2NOQEtTZE5QY11sb3oALwApNgAzHhgcHiMbHCAbHTU4NzYxLCYuNDlBNS4vMEAyNEA8S09SACgAJjAAMh0WFhMWFBIZERMnJygiJB4eHyAmKCEdHCQuIyEuKDAzNQAUABQdACcYFhMNExgPFA8TGyIpIh8dFhwaHx4fGRshJB4eJiElKi0AagCLlQCHVUY8OC84S19QfJKceJWVonKfiZmliIGDkYeCbo1oWFo+AL0Au6EAkFNCNTsqNVFXUHuPmGqPjKR7nIecp4WFg56UinKKZlBTOgB0AFQ1ADQfFhASDhYdFhMbIiEjKBcoJCwjKiUmKSY3NiwmJiEdIB4AQwAxJAAhHRMQEREVFBcRGCQbICEXHxwqIScgJCMkLS0jHyAZFxgWAD8AM0kATSIdGxwRERIWDhwfJSIjHBwaIx4fHx0bHx8iHBodFhgdHQAvAC1CAEIWGBoTEBYQFA0YGSYgIBsaFBgUFRYUERUVFhISFBAVGBkAFwAcHQAbCQkNCA4TCg4MERMcHBUXGA8MDA4PDQ0ODg8MCw0KDQ4PAD4AVGIAhHB5i5qenpyfnqOgeoh1ppubj4+fZZF7i4iTkZSWlJSQkgAvAFuCAI1/bpWWnbSvqqq1q464s8fCuL+8x5axmLWvy7q3zb/S0dcAGABAbQBYRjJFMjtHTE1OVFVofHpdbFxrZoB2YGJ2do9wa5J4m6qnABUAKkgARTEsKyoxJzE1NTlGUk1FND42REBaW0lSWVptTlhvWXmGhwAvAEZZAFgoHiovMTMvLyE0Qk9SSDk4MT86QEtAPT45TjpCTD1XXWUAMQBDSABKHRsmIB8lJyYZIyk5QDsoLSQmIzAzKSQkJjUrKTAqNTw8ABQAGxsAIAwNEAsMEBcSEA4QFSIhGRoSEhMaHRYUFBojGhogGiMkIwAUACxNAFk4Ojo8RjooLygwZHhiVU6AOldmY2hvTWJ1nnheald4emUATQB4iABrTUlGTVFOLywtQXymamlYo1tzgHaJkH+HneSrhpF4kZNwAFEAdF8APy4sJR4fLB4THiU5WDVLO1JERDk6T1RTUGaJcVZmTFVUQwA5AE4xACshHRwbFyIZGxscK0c0QTxJMz00OkZLQktneGpOZkFMTkAASwBlWQBHHCUuMjI2LSsqNUplU1dTUCpAOD5JQEFJX3FiUWpETU1EACwAQ0IAPBYgJSUnJSIdJS06QzxBODcbLiApLSkjLzpEPjM/LDIwLQAUAB0XABsMCw0MDg0PCxAUFRYcGxccEhkTGxsaFR0lLSUfJhodHRsAKgApLAAzIiQtNUhVSkdIUFNLS09QWU5OPk04TTpKVVpaVF9SU1BRACEAJGYAg2FXRkhxgmNidXN6eIqMfHVodniGhHRfdXeVf3OYhJKhnwAbAB5nAH1kXkcxVlhBXWZSV2SEgmdyU2h0ko1iaXyDnnlwnIOmtK8AFAAZLAA0NTYzJCssJUo+OC9HT1Q3WD5GQ2dYRE9QZm1WWHBieX16AB8ANkEARSwtODk+STxGO1FbgHpqSVI9Pj5PTkY5MUZbQkJfTlNfYQAnADY1ADoeHygrMDUyLSw3SVVUSzo6JSssNTEyICMnNicpOC0xOT8AHQAeHAAiFBERExASFA8VFxoXGx8ZHBIXGB8hHRUaGyIaHCUeIycoABYAGSsAKRcYFxQVHBQQFx4nIyopJCIcHxskLCIfISQzJCI0Jy4wMgCTAI1hAFgnLCUcKDgqMiUtQTpKSy4xNT8wMEQ2QkREUDc2Py4yLzYAjwB3UQBEIyAdGSI4JS4fHy80PzgoLzE1LjRDMTxBREIzNDkpJiUmADMAJRwAIBIPDgwRIBMWEQ0UISobGh4eHB0oKiIkJS4mIyMnGxgYFwAqADIqADkgJCYrNkAyMzdDWGlwZFBMOTkqLjUqLCowLigkLyAkKikALABGQgAvJR4jKTA3LS8zPlNiYV1GRC0vICczHyAhIykhHCYcIigpAB8AKC0AGhMMDAkLDw4QEhIYHSIbEhYNEQ8SGRAOEBMYERAUDxMUFgAmAB8pACcRExQRExYUEhgeKCUyJB4dFR0TEhgVEBQWGxUSGRMXGx4AKwBGbQB+TVUoNElLJ0NFRktlZnFTR0RXTUhsTkVNTnBWR21OdHlyACIASosAm1xiPEFUaTZfaWpsf3eNc3xke4N/j25sd4Wkh22tg7DBywAPACRCAEIrLCgfJzomR0JHRUZHVUlcQVNbYVlJVVFmclxUfl58hZ4AHAAqOAA+Ky8vJDcxKlE3S1RjcH9lX0taUWBlTE1PYHBOVG1UbHV8ADAAWVYATiUlLiQqJyIxLj1GW2NmUFNBSUVMUz4vQUhSOz5PQEdYVwAfAD86ACwbGxoSDxQSEhscGi4oKRwnHSUjJCckGyEpKyMjLiEqLzMAHgAkKgAnHSIiFxYYFxAZHyQ5LTQtKSEqICoiJSEkLjApJDImLzU1AKwAnl4AnmI1TUhfW0JQOzxvjJR1XXNVfl5/gWdfbGiOblp1S1tbTwDCAKZqAH9UKz05VVJATzY5and5YV5+VXJhdoNxY3R2mnxwg1FcXk4AbgBfSwAtIiAbERwZGx0bIS8yNiw9QS42Mz5HRkBSYHNnWmRASEw9AGAAc1AASygyIiEhIiAmLDxQbXJgT1JHXUxaaFtabYqVlXWAV2llUgB8AKJ6AIE6Mx4cIzMlLSg8WHNnX0lZUWZWUmpVVGV2hX1qa09WWEgAaQB+WgBdLiEWDBMjFh8ZJDRCMycnLTA4MTdCNjZBSlFDPUAxLzIoAFYARTwAQCEZEw8UIxEfFykzRTstJCszMjI+RD06OExJPzdBLy8wJQBPAEo8AJ+SjYqIgWNzanV6ipWBe4dxgI+YjIGTmY+BoJGElYeUkocATwBMZgC6kZ+doJdzmYGVj76wl5mlmpSpubejrLGvpcqyqc6y0ePPACYALmsAajc4MjJFQ0RIP0djW1JlSWFEV1hwaFtaX3OGZGaHcoqdmQAWACpMAEgwKBsjQ0IsPTQ+QVFHXTxGM0tBWV9LSlZgclJWZGVseoAAJwAzOgA/DyIeLDMwMzAwOzNCR2JTRTpcS01UQUNISl5LRFRRW2hzACkAOT4AURYfMTIkKzEpO0NENndiXk1YV0NdST5QOkVTQUFLQU5VZAAXACk6AEEbFzY0GiYlGVdMaDaTV2FCbz4tXDkuWSk/OCs1NioyPTwAbwCrxACxWEhiWV18cWCoi7i59d6uq9e1uLi6lq2GxZaJfJpuY2RQAKsAlagAqFlFVEtjfWJbr42rpv6zir2ym+qipqKff8SjhnyVdVtkXgBtAC8uADwgFy8qJi4lIHpicT/JPFmZfDicUy11Wi9RYjRCOjstQVEAQwAqLQAoGg8sKhseHhxTTHUvqixguIctfk0vm1gqSGksTDg4IjRCABkAGSAAHBAJDBILDAoNGR4rFTwiLko4GTInHDwqDyArEB8YFAwSFw==";

const FPS = 20;
const FRAME_COUNT = 121;
const BAR_COUNT = 40;
const MAX_HEIGHT = 64;
const MIN_HEIGHT = 2;

let decodedFrames: Uint8Array[] | null = null;

function getFrames(): Uint8Array[] {
  if (decodedFrames) return decodedFrames;
  const binary = atob(SPECTRUM_B64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  decodedFrames = [];
  for (let f = 0; f < FRAME_COUNT; f++) {
    decodedFrames.push(bytes.slice(f * BAR_COUNT, (f + 1) * BAR_COUNT));
  }
  return decodedFrames;
}

export function AudioDemo() {
  const barsRef = useRef<(HTMLDivElement | null)[]>([]);

  useEffect(() => {
    const frames = getFrames();
    const frameMs = 1000 / FPS;
    let raf: number;
    const start = performance.now();
    const current = new Float32Array(BAR_COUNT);

    function tick() {
      const elapsed = performance.now() - start;
      const exactFrame = (elapsed / frameMs) % FRAME_COUNT;
      const frameA = Math.floor(exactFrame);
      const frameB = (frameA + 1) % FRAME_COUNT;
      const t = exactFrame - frameA;

      const a = frames[frameA]!;
      const b = frames[frameB]!;

      for (let i = 0; i < BAR_COUNT; i++) {
        const el = barsRef.current[i];
        if (!el) continue;
        const target =
          MIN_HEIGHT + (a[i]! * (1 - t) + b[i]! * t) * ((MAX_HEIGHT - MIN_HEIGHT) / 255);
        // Exponential smoothing for extra fluidity
        current[i] += (target - current[i]) * 0.3;
        el.style.height = `${current[i]}px`;
      }

      raf = requestAnimationFrame(tick);
    }

    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, []);

  return (
    <div
      className="flex h-20 items-end gap-[1.5px]"
      style={{
        maskImage: "linear-gradient(to top, transparent 5%, black 20%)",
        WebkitMaskImage: "linear-gradient(to top, transparent 5%, black 20%)",
      }}
    >
      {Array.from({ length: BAR_COUNT }, (_, i) => (
        <div
          key={i}
          ref={(el) => {
            barsRef.current[i] = el;
          }}
          className="flex-1 rounded-t-full"
          style={{
            backgroundColor: "rgb(176,117,235)",
            height: MIN_HEIGHT,
            minHeight: MIN_HEIGHT,
          }}
        />
      ))}
    </div>
  );
}
